#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 12, 2017 07:53:10 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

from PIL import Image, ImageTk
from subprocess import call
import threading

def Plot(fx, x_l, x_u, canvas):
    print('support.Plot')

    p = threading.Thread(target=lambda: call(["python","plotit.py",'-f',fx, '-s', x_l, '-e', x_u ]) )
    p.start()
    p.join()

    gif1 = ImageTk.PhotoImage(image=Image.open("temp/generated_plot.png").resize((400,300),Image.ANTIALIAS))
    canvas.create_image(5,10, image = gif1, anchor = NW)
    canvas.gif1=gif1

    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui_main
    gui_main.vp_start_gui()


