#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 12, 2017 07:53:45 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    gui_support.init(root, top)
    root.protocol('WM_DELETE_WINDOW', destroy_app)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None

def destroy_app():
    global root
    root.destroy()
    exit(0)

class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("555x398+408+185")
        top.title("PlotIt")

        v = IntVar()

        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.04, rely=0.05, relheight=0.75, relwidth=0.72)
        self.Canvas1.configure(background="white")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(width=394)

        self.fx = Entry(top)
        self.fx.place(relx=0.11, rely=0.85, relheight=0.05, relwidth=0.53)
        self.fx.configure(background="white")
        self.fx.configure(font="TkFixedFont")
        self.fx.configure(width=296)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.77, rely=0.08, height=18, width=47)
        self.Label1.configure(text='''x lower''')

        self.x_lower = Entry(top)
        self.x_lower.place(relx=0.88, rely=0.08, relheight=0.05, relwidth=0.08)
        self.x_lower.configure(background="white")
        self.x_lower.configure(font="TkFixedFont")
        self.x_lower.configure(width=46)
        self.x_lower.insert(0, '0')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.77, rely=0.13, height=18, width=51)
        self.Label2.configure(text='''x upper''')

        self.x_upper = Entry(top)
        self.x_upper.place(relx=0.88, rely=0.13, relheight=0.05, relwidth=0.08)
        self.x_upper.configure(background="white")
        self.x_upper.configure(font="TkFixedFont")
        self.x_upper.configure(width=46)
        self.x_upper.insert(0, '100')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.04, rely=0.85, height=18, width=35)
        self.Label3.configure(text='''f(x)=''')

        self.bt_plot = Button(top)
        self.bt_plot.place(relx=0.67, rely=0.85, height=26, width=47)
        self.bt_plot.configure(activebackground="#d9d9d9")
        self.bt_plot.configure(command= lambda: gui_support.Plot(self.fx.get(), self.x_lower.get(), self.x_upper.get(), "#FFFF00", self.Canvas1))
        self.bt_plot.configure(cursor="fleur")
        self.bt_plot.configure(text='''Plot''')
        self.bt_plot.configure(width=47)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.78, rely=0.34, height=18, width=100)
        self.Label3.configure(text=" Choose the Color ")

        self.rd_btn1 = Radiobutton(top, text="Red   ", padx=20, variable=v, value=1)
        self.rd_btn1.pack(side = 'top', anchor = 'w')
        self.rd_btn1.place(relx=0.78, rely=0.40, height=18, width=60)
        self.rd_btn1.configure(command= lambda: gui_support.Plot(self.fx.get(), self.x_lower.get(), self.x_upper.get(), "#FF0000", self.Canvas1))

        self.rd_btn2 = Radiobutton(top, text="Blue  ", padx=20, variable=v, value=2)
        self.rd_btn2.pack(side = 'top', anchor = 'w')
        self.rd_btn2.place(relx=0.78, rely=0.46, height=18, width=60)
        self.rd_btn2.configure(command= lambda: gui_support.Plot(self.fx.get(), self.x_lower.get(), self.x_upper.get(), "#0000FF", self.Canvas1))

        self.rd_btn3 = Radiobutton(top, text="Cyan  ", padx=20, variable=v, value=3)
        self.rd_btn3.pack(side = 'top', anchor = 'w')
        self.rd_btn3.place(relx=0.78, rely=0.52, height=18, width=60)
        self.rd_btn3.configure(command= lambda: gui_support.Plot(self.fx.get(), self.x_lower.get(), self.x_upper.get(), "#00FFFF", self.Canvas1))

        self.rd_btn4 = Radiobutton(top, text="Black ", padx=20, variable=v, value=4)
        self.rd_btn4.pack(side = 'top', anchor = 'w')
        self.rd_btn4.place(relx=0.78, rely=0.58, height=18, width=60)
        self.rd_btn4.configure(command= lambda: gui_support.Plot(self.fx.get(), self.x_lower.get(), self.x_upper.get(), "#000000", self.Canvas1))

        self.rd_btn5 = Radiobutton(top, text="Green ", padx=20, variable=v, value=5)
        self.rd_btn5.pack(side = 'top', anchor = 'w')
        self.rd_btn5.place(relx=0.78, rely=0.64, height=18, width=60)
        self.rd_btn5.configure(command= lambda: gui_support.Plot(self.fx.get(), self.x_lower.get(), self.x_upper.get(), "#008000", self.Canvas1))

        self.color_input = Entry(top)
        self.color_input.place(relx=0.79, rely=0.70, relheight=0.05, relwidth=0.10)
        self.color_input.configure(background="white")
        self.color_input.configure(font="TkFixedFont")
        self.color_input.insert(0, '#ABCDEF')

        self.bt_go = Button(top)
        self.bt_go.place(relx=0.90, rely=0.70, height=20, width=40)
        self.bt_go.configure(activebackground="#d9d9d9")
        self.bt_go.configure(command= lambda: gui_support.Plot(self.fx.get(), self.x_lower.get(), self.x_upper.get(), self.color_input.get(), self.Canvas1))
        self.bt_go.configure(cursor="fleur")
        self.bt_go.configure(text='''Go''')
        self.bt_go.configure(width=47)

    @staticmethod
    def popup1(event):
        Popupmenu1 = Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.post(event.x_root, event.y_root)






if __name__ == '__main__':
    vp_start_gui()



